import { LEVELS } from './all-level.model';

LEVELS.levels.push({
    "id": "some-test-level",
    "name": "Tutorial Level",
    "description": "A generated level",
    "ordinal": 99,
    "board": [
        [
            { "key": "wall", "locked": true },
            { "key": "wall", "locked": true },
            { "key": "wall", "locked": true },
            { "key": "wall", "locked": true },
            { "key": "wall", "locked": true },
            { "key": "wall", "locked": true },
            { "key": "wall", "locked": true },
            { "key": "wall", "locked": true },
            { "key": "wall", "locked": true },
            { "key": "wall", "locked": true },
            { "key": "wall", "locked": true },
            { "key": "wall", "locked": true },
            { "key": "wall", "locked": true },
            { "key": "wall", "locked": true },
            { "key": "wall", "locked": true },
            { "key": "wall", "locked": true },
            { "key": "wall", "locked": true },
            { "key": "wall", "locked": true },
            { "key": "wall", "locked": true },
            { "key": "wall", "locked": true }
        ], [
            { "key": "wall", "locked": true },
            { "key": "player" },
            { "key": "free" },
            { "key": "free" },
            { "key": "free" },
            { "key": "wall" },
            { "key": "free" },
            { "key": "free" },
            { "key": "free" },
            { "key": "wall" },
            { "key": "free" },
            { "key": "free" },
            { "key": "free" },
            { "key": "free" },
            { "key": "free" },
            { "key": "free" },
            { "key": "free" },
            { "key": "free" },
            { "key": "free" },
            { "key": "wall", "locked": true }
        ], [
            { "key": "wall", "locked": true },
            { "key": "wall" },
            { "key": "wall" },
            { "key": "wall" },
            { "key": "free" },
            { "key": "wall" },
            { "key": "free" },
            { "key": "wall" },
            { "key": "free" },
            { "key": "wall" },
            { "key": "free" },
            { "key": "wall" },
            { "key": "wall" },
            { "key": "wall" },
            { "key": "wall" },
            { "key": "wall" },
            { "key": "wall" },
            { "key": "wall" },
            { "key": "free" },
            { "key": "wall", "locked": true }
        ], [
            { "key": "wall", "locked": true },
            { "key": "free" },
            { "key": "free" },
            { "key": "enemy" },
            { "key": "free" },
            { "key": "wall" },
            { "key": "free" },
            { "key": "wall" },
            { "key": "free" },
            { "key": "wall" },
            { "key": "free" },
            { "key": "wall" },
            { "key": "free" },
            { "key": "free" },
            { "key": "free" },
            { "key": "free" },
            { "key": "free" },
            { "key": "wall" },
            { "key": "free" },
            { "key": "wall", "locked": true }
        ], [
            { "key": "wall", "locked": true },
            { "key": "free" },
            { "key": "wall" },
            { "key": "wall" },
            { "key": "wall" },
            { "key": "wall" },
            { "key": "free" },
            { "key": "wall" },
            { "key": "free" },
            { "key": "wall" },
            { "key": "free" },
            { "key": "wall" },
            { "key": "free" },
            { "key": "wall" },
            { "key": "free" },
            { "key": "wall" },
            { "key": "free" },
            { "key": "wall" },
            { "key": "free" },
            { "key": "wall", "locked": true }
        ], [
            { "key": "wall", "locked": true },
            { "key": "free" },
            { "key": "free" },
            { "key": "free" },
            { "key": "free" },
            { "key": "free" },
            { "key": "free" },
            { "key": "wall" },
            { "key": "free" },
            { "key": "wall" },
            { "key": "free" },
            { "key": "wall" },
            { "key": "enemy" },
            { "key": "wall" },
            { "key": "free" },
            { "key": "wall" },
            { "key": "enemy" },
            { "key": "wall" },
            { "key": "free" },
            { "key": "wall", "locked": true }
        ], [
            { "key": "wall", "locked": true },
            { "key": "wall" },
            { "key": "wall" },
            { "key": "wall" },
            { "key": "wall" },
            { "key": "wall" },
            { "key": "wall" },
            { "key": "wall" },
            { "key": "free" },
            { "key": "wall" },
            { "key": "free" },
            { "key": "wall" },
            { "key": "key" },
            { "key": "wall" },
            { "key": "free" },
            { "key": "wall" },
            { "key": "key" },
            { "key": "wall" },
            { "key": "free" },
            { "key": "wall", "locked": true }
        ], [
            { "key": "wall", "locked": true },
            { "key": "free" },
            { "key": "free" },
            { "key": "free" },
            { "key": "free" },
            { "key": "free" },
            { "key": "free" },
            { "key": "free" },
            { "key": "free" },
            { "key": "wall" },
            { "key": "free" },
            { "key": "wall" },
            { "key": "wall" },
            { "key": "wall" },
            { "key": "free" },
            { "key": "wall" },
            { "key": "wall" },
            { "key": "wall" },
            { "key": "free" },
            { "key": "wall", "locked": true }
        ], [
            { "key": "wall", "locked": true },
            { "key": "free" },
            { "key": "wall" },
            { "key": "wall" },
            { "key": "wall" },
            { "key": "wall" },
            { "key": "wall" },
            { "key": "wall" },
            { "key": "wall" },
            { "key": "wall" },
            { "key": "free" },
            { "key": "free" },
            { "key": "free" },
            { "key": "free" },
            { "key": "free" },
            { "key": "free" },
            { "key": "free" },
            { "key": "free" },
            { "key": "free" },
            { "key": "wall", "locked": true }
        ], [
            { "key": "wall", "locked": true },
            { "key": "free" },
            { "key": "free" },
            { "key": "free" },
            { "key": "free" },
            { "key": "free" },
            { "key": "free" },
            { "key": "free" },
            { "key": "free" },
            { "key": "free" },
            { "key": "free" },
            { "key": "wall" },
            { "key": "wall" },
            { "key": "wall" },
            { "key": "wall" },
            { "key": "wall" },
            { "key": "wall" },
            { "key": "wall" },
            { "key": "closed door" },
            { "key": "wall", "locked": true }
        ], [
            { "key": "wall", "locked": true },
            { "key": "wall" },
            { "key": "wall" },
            { "key": "wall" },
            { "key": "wall" },
            { "key": "wall" },
            { "key": "wall" },
            { "key": "wall" },
            { "key": "wall" },
            { "key": "free" },
            { "key": "wall" },
            { "key": "free" },
            { "key": "free" },
            { "key": "free" },
            { "key": "free" },
            { "key": "free" },
            { "key": "free" },
            { "key": "wall" },
            { "key": "free" },
            { "key": "wall", "locked": true }
        ], [
            { "key": "wall", "locked": true },
            { "key": "free" },
            { "key": "free" },
            { "key": "free" },
            { "key": "hole" },
            { "key": "free" },
            { "key": "free" },
            { "key": "free" },
            { "key": "key" },
            { "key": "hole" },
            { "key": "wall" },
            { "key": "free" },
            { "key": "wall" },
            { "key": "wall" },
            { "key": "wall" },
            { "key": "wall" },
            { "key": "free" },
            { "key": "wall" },
            { "key": "free" },
            { "key": "wall", "locked": true }
        ], [
            { "key": "wall", "locked": true },
            { "key": "free" },
            { "key": "wall" },
            { "key": "wall" },
            { "key": "wall" },
            { "key": "wall" },
            { "key": "wall" },
            { "key": "wall" },
            { "key": "wall" },
            { "key": "wall" },
            { "key": "wall" },
            { "key": "free" },
            { "key": "wall" },
            { "key": "free" },
            { "key": "free" },
            { "key": "free" },
            { "key": "free" },
            { "key": "wall" },
            { "key": "free" },
            { "key": "wall", "locked": true }
        ], [
            { "key": "wall", "locked": true },
            { "key": "free" },
            { "key": "wall" },
            { "key": "free" },
            { "key": "enemy" },
            { "key": "free" },
            { "key": "wall" },
            { "key": "free" },
            { "key": "enemy" },
            { "key": "free" },
            { "key": "wall" },
            { "key": "free" },
            { "key": "wall" },
            { "key": "wall" },
            { "key": "wall" },
            { "key": "wall" },
            { "key": "wall" },
            { "key": "wall" },
            { "key": "free" },
            { "key": "wall", "locked": true }
        ], [
            { "key": "wall", "locked": true },
            { "key": "free" },
            { "key": "wall" },
            { "key": "free" },
            { "key": "wall" },
            { "key": "free" },
            { "key": "wall" },
            { "key": "free" },
            { "key": "wall" },
            { "key": "free" },
            { "key": "wall" },
            { "key": "free" },
            { "key": "closed door" },
            { "key": "free" },
            { "key": "free" },
            { "key": "free" },
            { "key": "free" },
            { "key": "hole" },
            { "key": "enemy" },
            { "key": "wall", "locked": true }
        ], [
            { "key": "wall", "locked": true },
            { "key": "free" },
            { "key": "wall" },
            { "key": "hole" },
            { "key": "wall" },
            { "key": "hole" },
            { "key": "wall" },
            { "key": "hole" },
            { "key": "wall" },
            { "key": "free" },
            { "key": "wall" },
            { "key": "free" },
            { "key": "wall" },
            { "key": "wall" },
            { "key": "wall" },
            { "key": "wall" },
            { "key": "wall" },
            { "key": "wall" },
            { "key": "closed door" },
            { "key": "wall", "locked": true }
        ], [
            { "key": "wall", "locked": true },
            { "key": "free" },
            { "key": "wall" },
            { "key": "free" },
            { "key": "wall" },
            { "key": "free" },
            { "key": "wall" },
            { "key": "free" },
            { "key": "wall" },
            { "key": "free" },
            { "key": "wall" },
            { "key": "free" },
            { "key": "wall" },
            { "key": "key" },
            { "key": "free" },
            { "key": "free" },
            { "key": "free" },
            { "key": "wall" },
            { "key": "enemy" },
            { "key": "wall", "locked": true }
        ], [
            { "key": "wall", "locked": true },
            { "key": "free" },
            { "key": "wall" },
            { "key": "free" },
            { "key": "wall" },
            { "key": "free" },
            { "key": "wall" },
            { "key": "free" },
            { "key": "wall" },
            { "key": "free" },
            { "key": "wall" },
            { "key": "free" },
            { "key": "wall" },
            { "key": "wall" },
            { "key": "wall" }, 
            { "key": "wall" }, 
            { "key": "free" }, 
            { "key": "wall" }, 
            { "key": "closed door" }, 
            { "key": "wall", "locked": true }
        ], [
            { "key": "wall", "locked": true }, 
            { "key": "free" }, 
            { "key": "enemy" }, 
            { "key": "free" }, 
            { "key": "wall" }, 
            { "key": "free" }, 
            { "key": "enemy" }, 
            { "key": "free" }, 
            { "key": "wall" }, 
            { "key": "free" }, 
            { "key": "enemy" }, 
            { "key": "free" }, 
            { "key": "free" }, 
            { "key": "free" }, 
            { "key": "free" }, 
            { "key": "free" }, 
            { "key": "free" }, 
            { "key": "wall" }, 
            { "key": "goal" }, 
            { "key": "wall", "locked": true }
        ], [
            { "key": "wall", "locked": true }, 
            { "key": "wall", "locked": true }, 
            { "key": "wall", "locked": true }, 
            { "key": "wall", "locked": true }, 
            { "key": "wall", "locked": true }, 
            { "key": "wall", "locked": true }, 
            { "key": "wall", "locked": true }, 
            { "key": "wall", "locked": true }, 
            { "key": "wall", "locked": true }, 
            { "key": "wall", "locked": true }, 
            { "key": "wall", "locked": true }, 
            { "key": "wall", "locked": true }, 
            { "key": "wall", "locked": true }, 
            { "key": "wall", "locked": true }, 
            { "key": "wall", "locked": true }, 
            { "key": "wall", "locked": true }, 
            { "key": "wall", "locked": true }, 
            { "key": "wall", "locked": true }, 
            { "key": "wall", "locked": true }, 
            { "key": "wall", "locked": true }
        ]
    ], 
    "startingCode": "for(let i = 0; i < 3; i++)\n\tPlayer.right();\nPlayer.down();\nPlayer.down();\n\n//Do some stuff", 
    "finishingCode": "", 
    "availableActions": ["move", "jump", "attack", "pickup", "use", "left", "right","up", "down"], 
    "maxMoves": 999, 
    "maxStamina": 999, 
    "gridSize": 20, 
    "icons": { 
        "wall": { 
            "key": "outdoor_garden", 
            "name": "wall", 
            "description": "An impassable object. Cannot be jumped or walked through" 
        }, 
        "hole": { 
            "key": "check_box_outline_blank", 
            "name": "hole", 
            "description": "An obstacle that needs to be jumped over." 
        }, 
        "free": { 
            "key": "texture", 
            "name": "free", 
            "description": "A free space that the player can stand on"
        }, 
        "goal": { 
            "key": "flag", 
            "name": "goal", 
            "description": "The objective of the level", 
            "max": 1 
        }, 
        "enemy": { 
            "key": "bug_report", 
            "name": "enemy", 
            "description": "An enemy that must be defeated in order to pass" 
        }, 
        "player": { 
            "key": "elderly_woman", 
            "name": "player", 
            "description": "The player's character", 
            "max": 1 
        }, 
        "key": { 
            "key": "key", 
            "name": "key", 
            "description": "A key the player can collect to open a door. Can only be used once." 
        }, 
        "closed door": { 
            "key": "door_front", 
            "name": "closed door", 
            "description": "A closed door that is impassable without a key." 
        }, 
        "opened door": { 
            "key": "door_open", 
            "name": "opened door", 
            "description": "A door that has been opened with a key." 
        } 
    }
});